helmDefaults:
  createNamespace: true
  cleanupOnFail: true
  force: true

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: ./kube-prometheus-stack

  - name: elasticsearch
    namespace: logging
    chart: ./elk-filebeat/elasticsearch

  - name: logstash
    namespace: logging
    chart: ./elk-filebeat/logstash
    needs:
      - logging/elasticsearch

  - name: kibana
    namespace: logging
    chart: ./elk-filebeat/kibana
    needs:
      - logging/elasticsearch
    hooks:
      - events: ["pre-upgrade"]
        command: "kubectl"
        args: ["delete", "configmap", "kibana-kibana-helm-scripts", "-n", "logging", "--ignore-not-found=true"]
      - events: ["pre-upgrade"]
        command: "kubectl"
        args: ["delete", "serviceaccount", "pre-install-kibana-kibana", "-n", "logging", "--ignore-not-found=true"]
      - events: ["pre-upgrade"]
        command: "kubectl"
        args: ["delete", "role", "pre-install-kibana-kibana", "-n", "logging", "--ignore-not-found=true"]
      - events: ["pre-upgrade"]
        command: "kubectl"
        args: ["delete", "rolebinding", "pre-install-kibana-kibana", "-n", "logging", "--ignore-not-found=true"]

  - name: filebeat
    namespace: logging
    chart: ./elk-filebeat/filebeat
    needs:
      - logging/elasticsearch
      - logging/logstash

  - name: jaeger
    namespace: tracing
    chart: ./jaeger
    needs:
      - logging/elasticsearch
