helmDefaults:
  createNamespace: true

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: ./kube-prometheus-stack

  - name: elasticsearch
    namespace: logging
    chart: ./elk-filebeat/elasticsearch

  - name: logstash
    namespace: logging
    chart: ./elk-filebeat/logstash
    needs:
      - logging/elasticsearch

  - name: kibana
    namespace: logging
    chart: ./elk-filebeat/kibana
    needs:
      - logging/elasticsearch

  - name: filebeat
    namespace: logging
    chart: ./elk-filebeat/filebeat
    needs:
      - logging/elasticsearch
      - logging/logstash

  - name: jaeger
    namespace: tracing
    chart: ./jaeger
    needs:
      - logging/elasticsearch
