apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger-tcp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jaeger
  ports:
    - name: query
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: http-thrift
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
  type: LoadBalancer