# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-jaeger-udp
#   namespace: {{ .Values.namespace }}
# spec:
#   selector:
#     app: jaeger
#   ports:
#     - name: agent-compact
#       port: 6831
#       protocol: UDP
#       targetPort: 6831
#   type: LoadBalancer
