# FROM tiangolo/uvicorn-gunicorn:python3.10

# RUN apt update && \
#     apt install -y htop libgl1-mesa-glx libglib2.0-0

# COPY requirements.txt /tmp/requirements.txt
# RUN pip install  --no-cache-dir -r /tmp/requirements.txt 

FROM tiangolo/uvicorn-gunicorn:python3.10

# Set working directory
WORKDIR /app

# Install dependencies
RUN apt update && \
    apt install -y htop libgl1-mesa-glx libglib2.0-0

# Copy and install requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
